### ISSUE TITLE
Error while training the model 

### ISSUE THREAD

**Issue by Saurak** [tomasz-oponowicz/spoken_language_identification#6]
Hi running model.py. I am getting following error 
Traceback (most recent call last):
  File "model.py", line 209, in <module>
    batch_size=8)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 1002, in fit
    validation_steps=validation_steps)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1630, in fit
    batch_size=batch_size)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1480, in _standardize_user_data
    exception_prefix='target')
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 123, in _standardize_input_data
    str(data_shape))
ValueError: Error when checking target: expected activation_6 to have shape (2,) but got array with shape (1,)

Can you please help me with this. Complete output is 
Using TensorFlow backend.
('Classes:', ['en', 'hi'])
[1, 2]
1
[1, 2]
[train] labels: (6960, 1), features: (6960, 40, 996, 1)
[1]
[train] labels: (3480, 1), features: (3480, 40, 996, 1)
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv2d_1 (Conv2D)            (None, 40, 996, 16)       160       
_________________________________________________________________
activation_1 (Activation)    (None, 40, 996, 16)       0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 20, 498, 16)       0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 20, 498, 32)       4640      
_________________________________________________________________
activation_2 (Activation)    (None, 20, 498, 32)       0         
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 10, 249, 32)       0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 10, 249, 64)       18496     
_________________________________________________________________
activation_3 (Activation)    (None, 10, 249, 64)       0         
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 5, 125, 64)        0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 5, 125, 128)       123008    
_________________________________________________________________
activation_4 (Activation)    (None, 5, 125, 128)       0         
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 5, 25, 128)        0         
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 5, 25, 256)        491776    
_________________________________________________________________
activation_5 (Activation)    (None, 5, 25, 256)        0         
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 5, 5, 256)         0         
_________________________________________________________________
average_pooling2d_1 (Average (None, 1, 1, 256)         0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 256)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 32)                8224      
_________________________________________________________________
dropout_1 (Dropout)          (None, 32)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 66        
_________________________________________________________________
activation_6 (Activation)    (None, 2)                 0         
=================================================================
Total params: 646,370
Trainable params: 646,370
Non-trainable params: 0
_________________________________________________________________
Traceback (most recent call last):
  File "model.py", line 209, in <module>
    batch_size=8)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 1002, in fit
    validation_steps=validation_steps)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1630, in fit
    batch_size=batch_size)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1480, in _standardize_user_data
    exception_prefix='target')
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 123, in _standardize_input_data
    str(data_shape))
ValueError: Error when checking target: expected activation_6 to have shape (2,) but got array with shape (1,)

**Comment by Saurak** [comment]
Fixed. Language list has to have 3 elements. Closing
